[package]
name = "pipelight_config"
version = "0.5.11"
edition = "2021"
license = "GPL-2.0-only"
description = "Multiple file format to rust struct"

[dependencies]
miette.workspace = true
pipelight_error = { path = "../pipelight_error" }
