[package]
name = "pipelight_config"
version = "0.5.10"
edition = "2021"
license = "GPL-2.0-only"
description = "Multiple file format to rust struct"

[dependencies]
pipelight_error = { path = "../pipelight_error" }
pipelight_exec = { path = "../pipelight_exec" }
pipelight_utils = { path = "../pipelight_utils" }
serde = { version = "1.0.208", features = ["derive"] }
miette = { version = "7.2.0" }
thiserror = "1.0.63"
log = "0.4.22"
serde_json = "1.0.125"
toml = { version = "0.8.19", features = ["parse"] }
hcl-rs = "0.18.0"
serde_yaml = "0.9.34"
kdl = "4.6.0"
serde_kdl = "0.1.0"
